name: 🚀 Production Deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build project
        run: npm run build

      - name: 📂 Sync build folder via FTP (Intento 1)
        id: ftp_deploy_1
        continue-on-error: true
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: dist/
          server: ftps4.us.freehostia.com
          username: estavi0
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: sheerit.com.co/
          security-mode: loose

      - name: ⏳ Pausa de 12 segundos si el servidor FTP rechazó la conexión
        if: steps.ftp_deploy_1.outcome == 'failure'
        run: sleep 12

      - name: 📂 Sync build folder via FTP (Intento 2 - Reintento Automático)
        if: steps.ftp_deploy_1.outcome == 'failure'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: dist/
          server: ftps4.us.freehostia.com
          username: estavi0
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: sheerit.com.co/
          security-mode: loose
