name: 🚀 Production Deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build project
        run: npm run build

      - name: 📂 Sync build folder via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: dist/
          server: ftps4.us.freehostia.com
          username: estavi0
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: sheerit.com.co/
          security-mode: loose
